type IFood = {
  foodname: string;
  image: string;
  ingredient: string[];
  desc: string[];
};

export const FoodList: IFood[] = [
  {
    foodname: "Abacha (African Salad)",
    image: "/Abacha.jpg",
    ingredient: [
      "2 cups of Abacha (cassava flakes)",
      "1-2 pieces of fish (dry or fried fish, e.g., mackerel)",
      "1 cup of palm oil",
      "1 teaspoon of potash (dissolved in warm water)",
      "1/2 cup of ugba (optional, oil bean seeds)",
      "2 tablespoons of ground crayfish",
      "To taste: pepper (fresh or ground)",
      "1 bulb of onions (sliced)",
      "1 teaspoon of ground ehuru (optional)",
      "1-2 seasoning cubes",
      "Salt to taste",
      "A handful of garden egg leaves (optional, chopped)",
    ],
    desc: [
      "Soak the Abacha in cold water for 5-10 minutes until soft. Drain and set aside.",
      "Dissolve the potash in warm water. Let it settle, then pour the clear liquid into a bowl, leaving the residue behind.",
      "In a clean bowl, pour the palm oil. Gradually add the potash solution while stirring until a thick, yellowish paste forms.",
      "Add ground crayfish, pepper, seasoning cubes, ground ehuru, and a pinch of salt into the oil mixture. Mix thoroughly.",
      "Add the softened Abacha and ugba (if using) into the palm oil mixture. Mix until the Abacha is well coated.",
      "Prepare the fish by either frying or soaking dry fish in warm salted water to soften, then clean and debone.",
      "Add the prepared fish to the Abacha mixture. Mix gently to incorporate.",
      "Garnish with sliced onions, chopped garden egg leaves, or scent leaves for extra flavor.",
      "Serve at room temperature with a drink of your choice.",
    ],
  },
  {
    foodname: "AKara (Beans Balls)",
    image: "/akara.jpg",
    ingredient: [
      "2 cups of peeled beans (black-eyed peas or brown beans)",
      "1 medium onion (chopped)",
      "2-3 fresh chili peppers or 1 teaspoon of ground pepper (adjust to taste)",
      "Salt to taste",
      "Vegetable oil (for frying)",
      "Optional: Crayfish (ground, for extra flavor)",
      "Optional: Sliced onions (for garnish or texture)",
    ],
    desc: [
      "Peel the beans by soaking them in water for a few minutes, then rubbing them between your palms to remove the skins. Rinse thoroughly until the water is clear, and the skins are removed.",
      "Blend the peeled beans with chopped onions and chili peppers using a blender. Add a small amount of water to assist blending but ensure the batter is thick and smooth.",
      "Pour the blended mixture into a mixing bowl. Add salt to taste and mix thoroughly. You can also add ground crayfish for extra flavor.",
      "Heat vegetable oil in a deep frying pan or pot over medium heat. Ensure the oil is hot enough before frying.",
      "Scoop small portions of the bean batter using a spoon and gently drop them into the hot oil. Fry in batches to avoid overcrowding.",
      "Fry until the Akara balls are golden brown and cooked through, turning them occasionally to ensure even frying.",
      "Remove the fried Akara balls with a slotted spoon and place them on paper towels to drain excess oil.",
    ],
  },
  {
    foodname: "Akidi & Abacha",
    image: "/Akidi and Abacha.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Alkubus",
    image: "/Alkubus.webp",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Atama (Soup)",
    image: "/Atama soup.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Balangu",
    image: "/Balangu.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Banga Rice",
    image: "/banga rice.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Banga Soup (Ofe Akwu)",
    image: "/Banga Soup.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Bitterleaf Soup",
    image: "/Bitterleaf Soup.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Boli",
    image: "/Boli.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Catfish Pepper Soup",
    image: "/Catfish Peppersoup.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Coconut Fried Rice ",
    image: "/Coconut Fried Rice.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Curry Sauce",
    image: "/curry sauce.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Edikaikong (Soup)",
    image: "/Edikaikong Soup.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Efo Riro (Soup)",
    image: "/Efo Riro.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Egg Sauce",
    image: "/Egg sauce and Yam.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Ofe Egusi (Soup)",
    image: "/Egusi soup.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Ekpang Nkukwo (Soup)",
    image: "/Ekpang Nkukwo.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Ewa Agoyin",
    image: "/Ewa Agoyin.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Ewedu (Soup)",
    image: "/Ewedu Soup.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Fankasu",
    image: "/Fankasu.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Fisherman Soup (Rivers Native Soup)",
    image: "/fisherman soup.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Fried Rice",
    image: "/fried rice.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Fry Plaintain",
    image: "/fry plaintain.jpg",
    ingredient: [],
    desc: [],
  },

  {
    foodname: "Gbegiri (Soup)",
    image: "/Gbegiri Soup.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Groudnut Soup",
    image: "/Groundnut Soup.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Gurasa",
    image: "Gurasa.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Garden egg sauce",
    image: "/Garden egg sauce.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Jollof Rice",
    image: "jollof rice.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Kiliahi",
    image: "/kilishi.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Kulikuli",
    image: "/kulikuli.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Miyan Geda (Soup)",
    image: "Miyan Geda.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Miyan Karkashi (Soup)",
    image: "/Miyan Karkashi.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Miyan Kuka (Soup)",
    image: "/miyan-kuka2.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Miyan Taushe (Soup)",
    image: "/Miyan Taushe.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Miyan Yakuwa (Soup)",
    image: "/Miyan Yakuwa.webp",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Miyan Zogale (Moringa Soup)",
    image: "/Miyan Zogale (Moringa Soup.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Moi Moi",
    image: "/moi moi.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Red Oil Rice",
    image: "/red oil rice.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Nkwobi",
    image: "/Nkwobi.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Ofe Nsala (Soup)",
    image: "/nsala.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Ofada Stew",
    image: "/Ofada Stew.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Ofe Achara (Soup)",
    image: "/OFE ACHARA.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Ogbono Soup",
    image: "/Ogbono Soup.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Ofe Oha (Soup)",
    image: "/Oha Soup (Ofe Oha).jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Okpa",
    image: "/okpa.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Okra Soup",
    image: "/Okra Soup.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Owo Soup",
    image: "/Owo soup.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Peanut Sauce",
    image: "/Peanut Sauce Recipe.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Pepper Soup",
    image: "/Pepper Soup.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Spaghetti",
    image: "/Spaghetti.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Suya",
    image: "suya.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Ugba",
    image: "/Ugba.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Ukodo",
    image: "/Ukodo.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Vegetable Sauce",
    image: "/vegetable sauce.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Waina",
    image: "/Waina.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Yam Porridge",
    image: "/yam.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Beans and Plaintain",
    image: "/Beans.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Beef Stew",
    image: "/Beef Stew.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Pap",
    image: "/pap.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Potato Porridge",
    image: "Potato Porridge.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Plantain Moi-moi (Ukpo Ogede)",
    image: "/Plantain Moi Moi (Ukpo Ogede).jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "YARIMATA-YAM",
    image: "/YARIMATA-YAM RECIPE.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Achicha-Ede",
    image: "/achicha-ede.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Agidi Eko",
    image: "/agidi-eko.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Agidi Jollof",
    image: "/agidi-jollof.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Boiled-white-coconut-rice",
    image: "/boiled-white-coconut-rice.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Ofe Akwu (Banga Stew)",
    image: "/Ofe Akwu (Banga Stew).jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Ofe Ugba (Oil Bean Soup)",
    image: "/Ofe Ugba (Oil Bean Soup).jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Peanut Soup",
    image: "/peanut_soup.webp",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Pepper Stew",
    image: "/pepper-stew.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Snail Soup (Ofe Ejula)",
    image: "/Snail soup, or “Ofe ejula,.webp",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Acha (Fonio) Swallow",
    image: "/Acha (Fonio).jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Amala (Swallow)",
    image: "/Amala.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Coleslaw Salad",
    image: "/coleselaw.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Eba (Swallow)",
    image: "/eba.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Fufu (Swallow)",
    image: "/fufu.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Plantain Swallow",
    image: "/Plantain Fufu.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Pounded Yam (Swallow)",
    image: "/Pounded Yam.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Salad",
    image: "/salad.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Semovita Semo (Swallow)",
    image: "/semo.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Tuwo Shinkafa (Swallow)",
    image: "/Tuwo Shinkafa.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "Starch (Swallow)",
    image: "/starch.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "wheat Swallow",
    image: "/wheat swallow.jpg",
    ingredient: [],
    desc: [],
  },
  {
    foodname: "",
    image: "",
    ingredient: [],
    desc: [],
  },
];
